package com.d2back.repository.enum

enum class ClassSkill {
    AMAZON_SKILL_LEVELS,
    ASSASSIN_SKILL_LEVELS,
    NECROMANCER_SKILL_LEVELS,
    BARBARIAN_SKILL_LEVELS,
    PALADIN_SKILL_LEVELS,
    SORCERESS_SKILL_LEVELS,
    DRUID_SKILL_LEVELS
}
