package com.d2back.repository.enum

enum class Key(val description: String) {
    COLD_ABSORB("Absorcion al frio &"),
    COLD_ABSORB_PERCENTAGE("Absorcion al frio &%"),
    FIRE_ABOSRB("Absorcion al fuego &"),
    FIRE_ABOSRB_PERCENTAGE("Absorcion al fuego &%"),
    LIGHTING_ABSORB("Absorcion a los rayos &"),
    LIGHTING_ABSORB_PERCENTAGE("Absorcion a los rayos &%"),
    MAGIC_ABSORB("Absorcion a la magia &"),
    MAGIC_ABSORB_PERCENTAGE("Absorcion a la magia &%"),
    ATTACK_RATING("& Puntuacion de ataque"),
    ATTACK_RATING_AGAINST_DEMONS("& Puntuacion de ataque contra demonios"),
    ATTACK_RATING_AGAINST_UNDEAD("& Puntuacion de ataque contra muertos vivientes"),
    BONUS_TO_ATTACK("&% Bonificación en el ataque"),
    FIRE_EXPLOSIVE_ARROWS("Dispara flechas explosivas"),
    FIRE_MAGIC_ARROWS("Dispara flechas magicas"),
    HIT_CAUSES_MONSTER_FLEE("El impacto hace que el monstruo huya un &%"),
    TARGET_DEFENSE("&% defensa del objetivo"),
    ONE_HAND_MIN_TO_MAX_DAMAGE("Añade &-& de daño"),
    TWO_HAND_MIN_TO_MAX_DAMAGE("Añade &-& de daño"),
    ATTACKER_TAKES_DAMAGE_OF("El atacante recibe el daño de &"),
    ATTACKER_TAKES_LIGHTING_DAMAGE_OF("El atacante recibe el daño de relampago de"),
    CHANCE_CRUSHING_BLOW("&% Posibilidad de golpe triturador"),
    CHANCE_DEADLY_STRIKE("&% azote mortal"),
    CHANCE_OPEN_WOUNDS("&% posibilidad de heridas abiertas"),
    COLD_DAMAGE("Añade &-& daño de frio"),
    DAMAGE("Daño &"),
    DAMAGE_TO_DEMONS("&% daño a los demonios"),
    DAMAGE_TO_MANA("&% daño infilgido que repercute en el mana"),
    DAMAGE_TO_UNDEAD("&% daño a los muertos vivientes"),
    ENHANCED_DAMAGE("&% daño mejorado"),
    ENHANCED_MAX_DAMAGE("&% daño maximo mejorado"),
    FIRE_DAMAGE("Añade &-& daño de fuego"),
    KICK_DAMAGE("&-& daño de patada"),
    LIGHTING_DAMAGE("Añade &-& daño de relampago"),
    MAGIC_DAMAGE("Añade &-& daño de magia"),
    MAX_ONE_HAND_DAMAGE("& al daño maximo"),
    MAX_TWO_HAND_DAMAGE("& al daño maximo"),
    MAX_COLD_DAMAGE("& al daño maximo de frio"),
    MAX_FIRE_DAMAGE("& al daño maximo de fuego"),
    MAX_LIGHTING_DAMAGE("& al daño maximo de relampago"),
    MAX_MAGIC_DAMAGE("& al daño maximo de magia"),
    MAX_POISON_DAMAGE("& al daño maximo de veneno"),
    MIN_ONE_HANDED_DAMAGE("& al daño minimo"),
    MIN_TWO_HANDED_DAMAGE("& al daño minimo"),
    POISON_DAMAGE("Añade &-& daño de veneno durante & segundos"),
    DEFENSE_VS_MELEE("& defensa contra refriega"),
    DEFENSE_VS_MISSILE("& defensa contra misil"),
    DEFENSE("& defensa"),
    REDUCE_MONSTER_DEFENSE_PER_HIT("& defensa del monstruo por golpe"),
    ENHANCED_DEFENSE("&% defensa perfeccionada"),
    EXPERIENCE("&% experiencia obtenida"),
    CHANCE_OF_GETTING_MAGIC_ITEMS("&% posibilidades de conseguir un objeto magico"),
    EXTRA_GOLD_FROM_MONSTERS("&% oro extra de los monstruos"),
    HEAL_AFTER_KILL("& de vida tras cada muerte"),
    INCREASED_SOCKETS("Engarzado (&)"),
    INCREASED_STACK_SIZE("Tamaño del monton aumentado"),
    LIGHT_RADIUS("& al radio de luz"),
    REDUCE_PRICES("Reduce el precio de todos los vendedores &%"),
    REPAIR_ONE_DURABILITY_IN_SECONDS("Repara 1 de durabilidad en & segundos"),
    REPLENLISH_ONE_QUANTITY_IN_SECONDS("Repone la cantidad (1 en & segundos)"),
    REQUERIMENTS("Requisitos &%"),
    ATTACK_FREEZES_TARGET("Congela al objetivo"),
    CANNOT_BE_FROZEN("No puede ser congelado"),
    CHANCE_OF_BLOCKING("&% aumenta la posibilidad de bloqueo"),
    CHANCE_TO_REANIMATE_TARGET("&% reanirmarse como: &"),
    HALF_FREEZE_DURATION("Mitad de duracion de congelamiento"),
    HEAL_STAMINA_PLUS("Curar resistencia extra &%"),
    HIT_BLINDS_TARGET("El impacto ciega al objetivo"),
    IGNORE_TARGET_DEFENSE("Ignorar defensa del objetivo"),
    INDESTRUCTIBLE("Indestructible"),
    KNOCK_BACK("El objetivo retrocede"),
    LIFE_AFTER_EACH_DEMON_KILL("& de vida tras cada muerte de demonio"),
    MANA_AFTER_EACH_KILL("& de mana tras cada muerte"),
    MAX_DURABILITY("Aumenta la durabilidad maxima un &%"),
    PREVENT_MONSTER_HEAL("Evita la curacion del monstruo"),
    REGENERATE_MANA("Regenerar mana &%"),
    REPLENLISH_LIFE("Repostar vida &"),
    REST_IN_PEACE("Matar monstruos"),
    SLOWER_STAMINA_DRAIN("&% drenaje de resistencia mas lento"),
    SLOWS_TARGET_BY("Realentiza al objetivo un &%"),
    THROWABLE("Arrojadizo"),
    PASSIVE_COLD_MASTERY("&% daño para la habilidad del frio"),
    PASSIVE_COLD_PIERCE("&% resistencia al frio enemigo"),
    PASSIVE_FIRE_MASTERY("&% daño para la habilidad del fuego"),
    PASSIVE_FIRE_PIERCE("&% resistencia al fuego enemigo"),
    PASSIVE_LIGHTING_MASTERY("&% daño para la habilidad del rayo"),
    PASSIVE_LIGHTING_PIERCE("&% resistencia al rayo enemigo"),
    PASSIVE_POISON_MASTERY("&% daño para la habilidad del veneno"),
    PASSIVE_POISON_PIERCE("&% resistencia al veneno enemigo"),
    DAMAGE_REDUCED_BY("Daño reducido en &"),
    DAMAGE_REDUCED_BY_PERCENTAGE("Daño reducido en &%"),
    MAGIC_DAMAGE_REDUCED_BY("Daño de magia reducido en &"),
    POISON_LENGTH_REDUCED_BY("Duracion del veneno reducida en un &%"),
    FIRE_RESISTANCE("Resistencia al fuego &%"),
    COLD_RESISTANCE("Resistencia al frio &%"),
    LIGHTING_RESISTANCE("Resistencia a los rayos &%"),
    POISON_RESISTANCE("Resistencia al veneno &%"),
    MAX_FIRE_RESISTANCE("&% a la resistencia maxima al fuego"),
    MAX_COLD_RESISTANCE("&% a la resistencia maxima al frio"),
    MAX_LIGHTING_RESISTANCE("&% a la resistencia maxima a los rayos"),
    MAX_POISON_RESISTANCE("&% a la resistencia maxima al veneno"),
    ALL_RESISTANCE("Todas las resistencias &%"),
    ALL_SKILLS("& a todas las habilidades"),
    AURA_WHEN_EQUIPPED("Nivel & aura & cuando esta equipada"),
    CHARGED_SKILL("Nivel & & (& cargas)"),
    CLASS_SKILL_LEVEL("& a los niveles de habilidad &"),
    FIRE_SKILLS("& a las habilidades de fuego"),
    NON_CLASS_SKILL("& para &"),
    SKILL_LEVELS("& para &"),
    SKILL_ON_ATTACK("&% posibilidades de lanzar el nivel & & al atacar"),
    SKILL_ON_DEATH("&% posibilidades de lanzar el nivel & & al morir"),
    SKILL_ON_HIT("&% posibilidades de lanzar el nivel & & al azotar"),
    SKILL_ON_LEVEL_UP("&% posibilidades de lanzar el nivel & & al subir de nivel"),
    SKILL_TAB_LEVELS("& para &"),
    SKILL_WHEN_STRUCK("&% posibilidades de lanzar el nivel & & al recibir un azote"),
    FASTER_BLOCK_RATE("&% velocidad de bloqueo mayor"),
    FASTER_CAST_RATE("&% velocidad de lanzamiento mayor"),
    FASTER_HIT_RECOVERY_RATE("&% recuperacion de impacto mas rapida"),
    FASTER_RUN_WALK("&% correr/andar mas rapido"),
    INCREASED_ATTACK_SPEED("&% velocidad de ataque aumentada"),
    DEXTRERITY("& de destreza"),
    ENERGY("& de energia"),
    LIFE("& de vida"),
    LIFE_PERCENTAGE("&% a la vida maxima"),
    MANA("& de mana"),
    MANA_PERCENTAGE("&% al mana maximo"),
    MAX_STAMINA("& a la resistencia maxima"),
    STRENGTH("& de fuerza"),
    VITALITY("& de vitalidad"),
    ALL_STATS("& a todos los atributos"),
    LIFE_STOLEN_PER_HIT("&% vida robada por impacto"),
    MANA_STOLEN_PER_HIT("&% mana robado por impacto"),
    COLD_ABSORB_PERCENTAGE_BY_LEVEL("&% absorbe el daño de frio muerto viviente"),
    FIRE_ABOSRB_PERCENTAGE_BY_LEVEL("&% absorbe el daño de fuego muerto viviente"),
    LIGHTING_ABSORB_PERCENTAGE_BY_LEVEL("&% absorbe el daño de relampago muerto viviente"),
    ATTACK_RATING_BY_LEVEL("& puntuacion de ataque muerto viviente"),
    ATTACK_RATING_AGAINST_DEMONS_BY_LEVEL("& puntuacion de ataque contra demonios muerto viviente"),
    ATTACK_RATING_AGAINST_UNDEAD_BY_LEVEL("& puntiacion de ataque contra muertos vivientes muerto viviente"),
    ATTACKER_TAKES_LIGHTING_DAMAGE_OF_BY_LEVEL("El atacante recibe el daño de relampago de & muerto viviente"),
    BONUS_TO_ATTACK_BY_LEVEL("&% bonificacion en el ataque muerto viviente"),
    CHANCE_CRUSHING_BLOW_BY_LEVEL("&% posibilidad de golpe triturador muerto viviente"),
    CHANCE_DEADLY_STRIKE_BY_LEVEL("&% azote mortal muerto viviente"),
    CHANCE_OPEN_WOUNDS_BY_LEVEL("&% posibilidad de heridas abiertas muerto viviente"),
    CHANCE_OF_GETTING_MAGIC_ITEMS_BY_LEVEL("&% posibilidades de conseguir un objeto magico muerto viviente"),
    COLD_RESISTANCE_BY_LEVEL("resistencia al frio &% muerto viviente"),
    FIRE_RESISTANCE_BY_LEVEL("resistencia al fuego &% muerto viviente"),
    LIGHTING_RESISTANCE_BY_LEVEL("resistencia a los rayos &% muerto viviente"),
    POISON_RESISTANCE_BY_LEVEL("resistencia al veneno &% muerto viviente"),
    DAMAGE_TO_DEMONS_BY_LEVEL("&% daño a los demonios muerto viviente"),
    DAMAGE_TO_MANA_BY_LEVEL("&% daño infilgido que repercute en el mana muerto viviente"),
    DAMAGE_TO_UNDEAD_BY_LEVEL("&% daño a los muertos vivientes muerto viviente"),
    DEFENSE_BY_LEVEL("& defense muerto viviente"),
    DEXTRERITY_BY_LEVEL("& de destreza muerto viviente"),
    ENERGY_BY_LEVEL("& de energia muerto viviente"),
    ENHACED_DEFENSE_BY_LEVEL("&% defensa perfeccionada muerto viviente"),
    ENHACED_MAX_DAMAGE_BY_LEVEL("&% daño maximo mejorado muerto viviente"),
    EXTRA_GOLD_FROM_MONSTERS_BY_LEVEL("&% oro extra de los monstruos muerto viviente"),
    HEAL_STAMINA_PLUS_BY_LEVEL("Curar resistencia extra &% muerto viviente"),
    KICK_DAMAGE_BY_LEVEL("& daño de patada muerto viviente"),
    LIFE_BY_LEVEL("& de vida muerto viviente"),
    MANA_BY_LEVEL("& de mana muerto viviente"),
    MAX_ONE_HAND_DAMAGE_BY_LEVEL("& al daño maximo muerto viviente"),
    MAX_COLD_DAMAGE_BY_LEVEL("& al daño maximo de frio muerto viviente"),
    MAX_FIRE_DAMAGE_BY_LEVEL("& al daño maximo de fuego muerto viviente"),
    MAX_LIGHTING_DAMAGE_BY_LEVEL("& al daño maximo de relampago muerto viviente"),
    MAX_POISON_DAMAGE_BY_LEVEL("& al daño maximo de veneno muerto viviente"),
    MAX_STAMINA_BY_LEVEL("& a la resistencia maxima muerto viviente"),
    STRENGTH_BY_LEVEL("& de fuerza muerto viviente"),
    VITALITY_BY_LEVEL("& de vitalidad muerto viviente"),
}
