package com.d2back.model.enums

enum class Key(val description: String) {
    cold_absorb("Absorcion al frio &"),
    cold_absorb_percentage("Absorcion al frio &%"),
    fire_absorb("Absorcion al fuego &"),
    fire_absorb_percentage("Absorcion al fuego &%"),
    lighting_absorb("Absorcion a los rayos &"),
    lighting_absorb_percentage("Absorcion a los rayos &%"),
    magic_absorb("Absorcion a la magia &"),
    magic_absorb_percentage("Absorcion a la magia &%"),
    attack_rating("& puntuacion de ataque"),
    attack_rating_against_demons("& puntuacion de ataque contra demonios"),
    attack_rating_against_undead("& puntuacion de ataque contra muertos vivientes"),
    bonus_to_attack("&% bonificación en el ataque"),
    fire_explosive_arrows("Dispara flechas explosivas"),
    fire_magic_arrows("Dispara flechas magicas"),
    hit_causes_monster_flee("El impacto hace que el monstruo huya un &%"),
    target_defense("&% defensa del objetivo"),
    one_hand_min_to_max_damage("Añade &-& de daño"),
    two_hand_min_to_max_damage("Añade &-& de daño"),
    attacker_takes_damage_of("El atacante recibe el daño de &"),
    attacker_takes_lighting_damage_of("El atacante recibe el daño de relampago de"),
    chance_crushing_blow("&% posibilidad de golpe triturador"),
    chance_deadly_strike("&% azote mortal"),
    chance_open_wounds("&% posibilidad de heridas abiertas"),
    cold_damage("Añade &-& daño de frio"),
    damage("Daño &"),
    damage_to_demons("&% daño a los demonios"),
    damage_to_mana("&% daño infilgido que repercute en el mana"),
    damage_to_undead("&% daño a los muertos vivientes"),
    enhanced_damage("&% daño mejorado"),
    enhanced_max_damage("&% daño maximo mejorado"),
    fire_damage("Añade &-& daño de fuego"),
    kick_damage("&-& daño de patada"),
    lighting_damage("Añade &-& daño de relampago"),
    magix_damage("Añade &-& daño de magia"),
    max_one_hand_damage("& al daño maximo"),
    max_two_hand_damage("& al daño maximo"),
    max_cold_damage("& al daño maximo de frio"),
    max_fire_damage("& al daño maximo de fuego"),
    max_lighting_damage("& al daño maximo de relampago"),
    max_magic_damage("& al daño maximo de magia"),
    max_poison_damage("& al daño maximo de veneno"),
    min_one_handed_damage("& al daño minimo"),
    min_two_handed_damage("& al daño minimo"),
    poison_damage("Añade &-& daño de veneno durante & segundos"),
    denfese_vs_melee("& defensa contra refriega"),
    defense_vs_missile("& defensa contra misil"),
    defense("& defensa"),
    reduce_monster_defense_per_hit("& defensa del monstruo por golpe"),
    enhanced_defense("&% defensa perfeccionada"),
    experience("&% experiencia obtenida"),
    chance_of_getting_magic_items("&% posibilidades de conseguir un objeto magico"),
    extra_gold_from_monsters("&% oro extra de los monstruos"),
    heal_after_kill("& de vida tras cada muerte"),
    incresed_sockets("Engarzado (&)"),
    increased_stack_size("Tamaño del monton aumentado"),
    light_radius("& al radio de luz"),
    reduce_prices("Reduce el precio de todos los vendedores &%"),
    repair_one_durability_in_seconds("Repara 1 de durabilidad en & segundos"),
    replenlish_one_quantity_in_seconds("Repone la cantidad (1 en & segundos)"),
    requeriments("Requisitos &%"),
    attack_freezes_target("Congela al objetivo"),
    cannot_be_frozen("No puede ser congelado"),
    chance_of_blocking("&% aumenta la posibilidad de bloqueo"),
    chance_to_reanimate_target("&% reanirmarse como: &"),
    half_freeze_duration("Mitad de duracion de congelamiento"),
    heal_stamina_plus("Curar resistencia extra &%"),
    hit_blinds_target("El impacto ciega al objetivo"),
    ignore_target_defense("Ignorar defensa del objetivo"),
    indestructible("Indestructible"),
    knock_back("El objetivo retrocede"),
    life_after_each_demon_kill("& de vida tras cada muerte de demonio"),
    mana_after_each_kill("& de mana tras cada muerte"),
    max_durability("Aumenta la durabilidad maxima un &%"),
    prevent_monster_heal("Evita la curacion del monstruo"),
    regenerate_mana("Regenerar mana &%"),
    replenlish_life("Repostar vida &"),
    rest_in_peace("Matar monstruos"),
    slower_stamina_drain("&% drenaje de resistencia mas lento"),
    slows_target_by("Realentiza al objetivo un &%"),
    throwable("Arrojadizo"),
    passive_cold_mastery("&% daño para la habilidad del frio"),
    passive_cold_pierce("&% resistencia al frio enemigo"),
    passive_fire_mastery("&% daño para la habilidad del fuego"),
    passive_fire_pierce("&% resistencia al fuego enemigo"),
    passive_lighting_mastery("&% daño para la habilidad del rayo"),
    passive_lighting_pierce("&% resistencia al rayo enemigo"),
    passive_poison_mastery("&% daño para la habilidad del veneno"),
    passive_poison_pierce("&% resistencia al veneno enemigo"),
    damage_reduced_by("Daño reducido en &"),
    damage_reduced_by_percentage("Daño reducido en &%"),
    magic_damage_reduced_by("Daño de magia reducido en &"),
    poison_length_reduced_by("Duracion del veneno reducida en un &%"),
    fire_resistance("Resistencia al fuego &%"),
    cold_resistance("Resistencia al frio &%"),
    lighting_resistance("Resistencia a los rayos &%"),
    poison_resistance("Resistencia al veneno &%"),
    max_fire_resistance("&% a la resistencia maxima al fuego"),
    max_cold_resistance("&% a la resistencia maxima al frio"),
    max_lighting_resistance("&% a la resistencia maxima a los rayos"),
    max_poison_resistance("&% a la resistencia maxima al veneno"),
    all_resistance("Todas las resistencias &%"),
    all_skills("& a todas las habilidades"),
    aura_when_equipped("Nivel & aura & cuando esta equipada"),
    charged_skill("Nivel & & (& cargas)"),
    class_skill_level("& a los niveles de habilidad &"),
    fire_skills("& a las habilidades de fuego"),
    non_class_skill("& para &"),
    skill_levels("& para &"),
    skill_on_attack("&% posibilidades de lanzar el nivel & & al atacar"),
    skill_on_death("&% posibilidades de lanzar el nivel & & al morir"),
    skill_on_hit("&% posibilidades de lanzar el nivel & & al azotar"),
    skill_on_level_up("&% posibilidades de lanzar el nivel & & al subir de nivel"),
    skill_tab_levels("& para &"),
    skill_when_struck("&% posibilidades de lanzar el nivel & & al recibir un azote"),
    faster_block_rate("&% velocidad de bloqueo mayor"),
    faster_cast_rate("&% velocidad de lanzamiento mayor"),
    faster_hit_recovery_rate("&% recuperacion de impacto mas rapida"),
    faster_run_walk("&% correr/andar mas rapido"),
    increased_attack_speed("&% velocidad de ataque aumentada"),
    dextrerity("& de destreza"),
    energy("& de energia"),
    life("& de vida"),
    life_percentage("&% a la vida maxima"),
    mana("& de mana"),
    mana_percentage("&% al mana maximo"),
    max_stamina("& a la resistencia maxima"),
    strength("& de fuerza"),
    vitality("& de vitalidad"),
    all_stats("& a todos los atributos"),
    life_stolen_per_hit("&% vida robada por impacto"),
    mana_stolen_per_hit("&% mana robado por impacto"),
    cold_absorb_percentage_by_level("&% absorbe el daño de frio muerto viviente"),
    fire_abosrb_percentage_by_level("&% absorbe el daño de fuego muerto viviente"),
    lighting_absorb_percentage_by_level("&% absorbe el daño de relampago muerto viviente"),
    attack_rating_by_level("& puntuacion de ataque muerto viviente"),
    attack_rating_against_demons_by_level("& puntuacion de ataque contra demonios muerto viviente"),
    attack_rating_against_undead_by_level("& puntiacion de ataque contra muertos vivientes muerto viviente"),
    attacker_takes_lighting_damage_of_by_level("El atacante recibe el daño de relampago de & muerto viviente"),
    bonus_to_attack_by_level("&% bonificacion en el ataque muerto viviente"),
    chance_crushing_blow_by_level("&% posibilidad de golpe triturador muerto viviente"),
    chance_deadly_strike_by_level("&% azote mortal muerto viviente"),
    chance_open_wounds_by_level("&% posibilidad de heridas abiertas muerto viviente"),
    chance_of_getting_magic_items_by_level("&% posibilidades de conseguir un objeto magico muerto viviente"),
    cold_resistance_by_level("Resistencia al frio &% muerto viviente"),
    fire_resistance_by_level("Resistencia al fuego &% muerto viviente"),
    lighting_resistance_by_level("Resistencia a los rayos &% muerto viviente"),
    poison_resistance_by_level("Resistencia al veneno &% muerto viviente"),
    damage_to_demons_by_level("&% daño a los demonios muerto viviente"),
    damage_to_mana_by_level("&% daño infilgido que repercute en el mana muerto viviente"),
    damage_to_undead_by_level("&% daño a los muertos vivientes muerto viviente"),
    defense_by_level("& defense muerto viviente"),
    dextrerity_by_level("& de destreza muerto viviente"),
    energy_by_level("& de energia muerto viviente"),
    enhaced_defense_by_level("&% defensa perfeccionada muerto viviente"),
    enhaced_max_damage_by_level("&% daño maximo mejorado muerto viviente"),
    extra_gold_from_monsters_by_level("&% oro extra de los monstruos muerto viviente"),
    heal_stamina_plus_by_level("Curar resistencia extra &% muerto viviente"),
    kick_damage_by_level("& daño de patada muerto viviente"),
    life_by_level("& de vida muerto viviente"),
    mana_by_level("& de mana muerto viviente"),
    max_one_hand_damage_by_level("& al daño maximo muerto viviente"),
    max_cold_damage_by_level("& al daño maximo de frio muerto viviente"),
    max_fire_damage_by_level("& al daño maximo de fuego muerto viviente"),
    max_lighting_damage_by_level("& al daño maximo de relampago muerto viviente"),
    max_poison_damage_by_level("& al daño maximo de veneno muerto viviente"),
    max_stamina_by_level("& a la resistencia maxima muerto viviente"),
    strength_by_level("& de fuerza muerto viviente"),
    vitality_by_level("& de vitalidad muerto viviente"),
}
