spring:
  application:
    name: d2back
    description: Repositorio con almacenamiento de todo el sistema de items + skills Diablo II
    version: 1.0.0
  profiles:
    active: ${PDB_SERVICE_ENV:development}
  webflux:
    base-path: /api
  data:
    mongodb:
      uri: "mongodb://localhost:27017/d2back?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}
  env:
    profile: ${spring.profiles.active}

config-map:
  environment: ${spring.profiles.active}
  security:
    apiUsers:
      clienteEjemplo: "1234"
      clienteEjemplo2: "5678"

graphql:
  packages: "com.d2back.graphql"
  endpoint: "api/graphql"
  federation:
    enabled: true
  playground:
    enabled: true
    endpoint: "api/playground"
  sdl:
    enabled: true
    endpoint: "api/sdl"

management:
  endpoints:
    enabled-by-default: false
    web:
      cors:
        allowed-origins: "*.ar.bsch"
        allowed-methods: GET,HEAD
      exposure:
        include: "*"
      base-path: "/metrics"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
