package com.d2back.model.enum

enum class TabSkill {
    BOW_CROSSBOW_SKILLS,
    PASSIVE_MAGIC_SKILLS,
    JAVELIN_SPEAR_SKILLS,
    FIRE_SKILLS,
    LIGHTING_SKILLS,
    COLD_SKILLS,
    CURSES,
    POISON_BONE_SKILLS,
    SUMMONING,
    COMBAT_SKILLS_PALADIN,
    OFFENSIVE_AURAS,
    DEFENSIVE_AURAS,
    COMBAT_SKILLS_BARBARIAN,
    MASTERIES,
    WARCRIES,
    SUMMONING_DRUID,
    SHAPE_SHIFTING_SKILLS,
    ELEMENTAL_SKILLS,
    TRAPS,
    SHADOW_DISPLINES,
    MARTIAL_ARTS
}
